In [2]:
import pandas as pd

In [3]:
nav = pd.read_csv("data/raw/02_nav_history.csv")

nav['date'] = pd.to_datetime(nav['date'])
nav = nav.sort_values(['amfi_code', 'date'])
nav = nav.drop_duplicates()
nav = nav[nav['nav'] > 0]
nav['nav'] = nav.groupby('amfi_code')['nav'].ffill()

nav.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [4]:
nav.to_csv("data/processed/nav_clean.csv", index=False)
print("NAV SAVED")

NAV SAVED

In [6]:
txn = pd.read_csv("data/raw/08_investor_transactions.csv")
txn.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='object')

In [7]:
txn = pd.read_csv("data/raw/08_investor_transactions.csv")

# correct date column
txn['transaction_date'] = pd.to_datetime(txn['transaction_date'])

# standardize type
txn['transaction_type'] = txn['transaction_type'].str.upper()

# filter valid types
txn = txn[txn['transaction_type'].isin(['SIP', 'LUMPSUM', 'REDEMPTION'])]

# amount column is also different name
txn = txn[txn['amount_inr'] > 0]

txn.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,REDEMPTION,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,LUMPSUM,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [8]:
import pandas as pd

txn = pd.read_csv("data/raw/08_investor_transactions.csv")

# date fix
txn['transaction_date'] = pd.to_datetime(txn['transaction_date'])

# standardize transaction type
txn['transaction_type'] = txn['transaction_type'].str.upper()

# valid types only
txn = txn[txn['transaction_type'].isin(['SIP', 'LUMPSUM', 'REDEMPTION'])]

# amount filter
txn = txn[txn['amount_inr'] > 0]

txn.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,REDEMPTION,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,LUMPSUM,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [9]:
import pandas as pd

txn = pd.read_csv("data/raw/08_investor_transactions.csv")

# date convert
txn['transaction_date'] = pd.to_datetime(txn['transaction_date'])

# standardize type
txn['transaction_type'] = txn['transaction_type'].str.upper()

# keep only valid types
txn = txn[txn['transaction_type'].isin(['SIP', 'LUMPSUM', 'REDEMPTION'])]

# amount validation
txn = txn[txn['amount_inr'] > 0]

# check KYC values (optional validation)
txn = txn[txn['kyc_status'].isin(['Verified', 'Pending'])]

txn.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,REDEMPTION,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,LUMPSUM,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [10]:
import pandas as pd

txn = pd.read_csv("data/raw/08_investor_transactions.csv")

# 1. date convert
txn['transaction_date'] = pd.to_datetime(txn['transaction_date'])

# 2. standardize transaction type
txn['transaction_type'] = txn['transaction_type'].str.upper()

# 3. keep only valid types
txn = txn[txn['transaction_type'].isin(['SIP', 'LUMPSUM', 'REDEMPTION'])]

# 4. validate amount
txn = txn[txn['amount_inr'] > 0]

# 5. kyc validation
txn = txn[txn['kyc_status'].isin(['Verified', 'Pending'])]

# 6. final check
txn.info()
txn.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  datetime64[ns]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,REDEMPTION,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,LUMPSUM,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [11]:
import pandas as pd

txn = pd.read_csv("data/raw/08_investor_transactions.csv")

# date conversion
txn['transaction_date'] = pd.to_datetime(txn['transaction_date'])

# standardize transaction type
txn['transaction_type'] = txn['transaction_type'].str.upper()

# valid types only
txn = txn[txn['transaction_type'].isin(['SIP', 'LUMPSUM', 'REDEMPTION'])]

# amount check
txn = txn[txn['amount_inr'] > 0]

# kyc check
txn = txn[txn['kyc_status'].isin(['Verified', 'Pending'])]

# final preview
print(txn.head())
print(txn.info())

  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       REDEMPTION      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          LUMPSUM        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  datetime64[ns]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB
None

In [12]:
import pandas as pd

perf = pd.read_csv("data/raw/07_scheme_performance.csv")

perf.head()
perf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [13]:
import pandas as pd

perf = pd.read_csv("data/raw/07_scheme_performance.csv")

# 1. basic check
print(perf.info())

# 2. ensure numeric columns are correct (safe step)
num_cols = [
    'return_1yr_pct','return_3yr_pct','return_5yr_pct',
    'benchmark_3yr_pct','alpha','beta','sharpe_ratio',
    'sortino_ratio','std_dev_ann_pct','max_drawdown_pct',
    'aum_crore','expense_ratio_pct','morningstar_rating'
]

for col in num_cols:
    perf[col] = pd.to_numeric(perf[col], errors='coerce')

# 3. remove nulls (safety)
perf = perf.dropna()

# 4. expense ratio filter (0.1% - 2.5%)
perf = perf[(perf['expense_ratio_pct'] >= 0.1) & (perf['expense_ratio_pct'] <= 2.5)]

# 5. final check
perf.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB
None

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [14]:
perf.to_csv("data/processed/performance_clean.csv", index=False)
print("PERFORMANCE CLEAN DONE")

PERFORMANCE CLEAN DONE

In [15]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("bluestock_mf.db")
cursor = conn.cursor()

print("Database created")

Database created

In [16]:
cursor.executescript("""
CREATE TABLE IF NOT EXISTS dim_fund (
    amfi_code INTEGER PRIMARY KEY,
    scheme_name TEXT,
    fund_house TEXT,
    category TEXT,
    plan TEXT
);

CREATE TABLE IF NOT EXISTS fact_nav (
    amfi_code INTEGER,
    date TEXT,
    nav REAL
);

CREATE TABLE IF NOT EXISTS fact_transactions (
    investor_id TEXT,
    transaction_date TEXT,
    amfi_code INTEGER,
    transaction_type TEXT,
    amount_inr REAL,
    state TEXT,
    city TEXT,
    city_tier TEXT,
    age_group TEXT,
    gender TEXT,
    annual_income_lakh REAL,
    payment_mode TEXT,
    kyc_status TEXT
);

CREATE TABLE IF NOT EXISTS fact_performance (
    amfi_code INTEGER,
    return_1yr_pct REAL,
    return_3yr_pct REAL,
    return_5yr_pct REAL,
    benchmark_3yr_pct REAL,
    alpha REAL,
    beta REAL,
    sharpe_ratio REAL,
    sortino_ratio REAL,
    std_dev_ann_pct REAL,
    max_drawdown_pct REAL,
    expense_ratio_pct REAL,
    morningstar_rating INTEGER,
    risk_grade TEXT
);
""")

print("Tables created successfully")

Tables created successfully

In [17]:
import pandas as pd
import sqlite3

In [18]:
conn = sqlite3.connect("bluestock_mf.db")

In [20]:
import os

print(os.listdir("data"))

['processed', 'raw']

In [21]:
import os
os.listdir("data/processed")

['nav_clean.csv', 'performance_clean.csv']

In [22]:
txn.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,REDEMPTION,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,LUMPSUM,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [23]:
import os

os.makedirs("data/processed", exist_ok=True)

txn.to_csv("data/processed/transactions_clean.csv", index=False)

print("transactions_clean.csv SAVED SUCCESSFULLY")

transactions_clean.csv SAVED SUCCESSFULLY

In [24]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("bluestock_mf.db")

print("Connected to database")

Connected to database

In [25]:
import pandas as pd

fund = pd.read_csv("data/raw/01_fund_master.csv")
fund.to_sql("dim_fund", conn, if_exists="replace", index=False)

print("dim_fund loaded")

dim_fund loaded

In [26]:
nav = pd.read_csv("data/processed/nav_clean.csv")
nav.to_sql("fact_nav", conn, if_exists="replace", index=False)

print("fact_nav loaded")

fact_nav loaded

In [27]:
nav = pd.read_csv("data/processed/nav_clean.csv")
nav.to_sql("fact_nav", conn, if_exists="replace", index=False)

print("fact_nav loaded")

fact_nav loaded

In [28]:
txn = pd.read_csv("data/processed/transactions_clean.csv")
txn.to_sql("fact_transactions", conn, if_exists="replace", index=False)

print("fact_transactions loaded")

fact_transactions loaded

In [29]:
perf = pd.read_csv("data/processed/performance_clean.csv")
perf.to_sql("fact_performance", conn, if_exists="replace", index=False)

print("fact_performance loaded")

fact_performance loaded

In [30]:
print(pd.read_sql("SELECT COUNT(*) FROM dim_fund", conn))
print(pd.read_sql("SELECT COUNT(*) FROM fact_nav", conn))
print(pd.read_sql("SELECT COUNT(*) FROM fact_transactions", conn))
print(pd.read_sql("SELECT COUNT(*) FROM fact_performance", conn))

   COUNT(*)
0        40
   COUNT(*)
0     46000
   COUNT(*)
0     32778
   COUNT(*)
0        40

In [31]:
pd.read_sql("""
SELECT scheme_name, aum_crore
FROM fact_performance
ORDER BY aum_crore DESC
LIMIT 5;
""", conn)

                                         scheme_name  aum_crore
0  Mirae Asset Emerging Bluechip Fund - Regular -...      49046
1      Kotak Emerging Equity Fund - Regular - Growth      47469
2     Nippon India Small Cap Fund - Regular - Growth      43630
3         DSP Top 100 Equity Fund - Regular - Growth      41828
4                UTI Mid Cap Fund - Regular - Growth      41728

In [32]:
pd.read_sql("""
SELECT transaction_type, COUNT(*) as total_transactions,
       SUM(amount_inr) as total_amount
FROM fact_transactions
GROUP BY transaction_type;
""", conn)

  transaction_type  total_transactions  total_amount
0          LUMPSUM                8095    2059821448
1       REDEMPTION                4967    1244525491
2              SIP               19716     217233491

In [33]:
pd.read_sql("""
SELECT state, 
       COUNT(*) as total_transactions,
       SUM(amount_inr) as total_invested
FROM fact_transactions
GROUP BY state
ORDER BY total_invested DESC
LIMIT 10;
""", conn)

            state  total_transactions  total_invested
0          Punjab                2965       315780459
1      Tamil Nadu                2806       315177237
2  Madhya Pradesh                2931       308312493
3       Rajasthan                2577       298645822
4         Gujarat                2780       298358940
5     West Bengal                2748       297182514
6       Telangana                2718       290219284
7           Delhi                2677       289633404
8   Uttar Pradesh                2695       285368873
9         Haryana                2736       279634354

In [34]:
pd.read_sql("""
SELECT scheme_name, return_1yr_pct
FROM fact_performance
ORDER BY return_1yr_pct DESC
LIMIT 5;
""", conn)

                                      scheme_name  return_1yr_pct
0          ABSL Small Cap Fund - Regular - Growth           24.93
1      SBI Small Cap Fund - Regular Plan - Growth           24.56
2          Axis Small Cap Fund - Regular - Growth           21.97
3  Nippon India Small Cap Fund - Regular - Growth           21.30
4       SBI Small Cap Fund - Direct Plan - Growth           20.59

In [35]:
pd.read_sql("""
SELECT scheme_name, expense_ratio_pct
FROM fact_performance
WHERE expense_ratio_pct < 1
ORDER BY expense_ratio_pct ASC;
""", conn)

                                          scheme_name  expense_ratio_pct
0   Nippon India Gilt Securities Fund - Regular - ...               0.55
1        HDFC Short Term Debt Fund - Regular - Growth               0.56
2                Kotak Liquid Fund - Regular - Growth               0.60
3            SBI Bluechip Fund - Direct Plan - Growth               0.66
4           SBI Small Cap Fund - Direct Plan - Growth               0.72
5       Nippon India Large Cap Fund - Direct - Growth               0.72
6            ICICI Pru Liquid Fund - Regular - Growth               0.74
7                Axis Bluechip Fund - Direct - Growth               0.75
8        SBI Magnum Gilt Fund - Regular Plan - Growth               0.77
9   HDFC Mid-Cap Opportunities Fund - Direct - Growth               0.78
10                ABSL Liquid Fund - Regular - Growth               0.79
11          ICICI Pru Bluechip Fund - Direct - Growth               0.80
12                     Nippon India ETF Nifty 50 BeES               0.89
13           HDFC Top 100 Fund - Direct Plan - Growth               0.92

In [36]:
pd.read_sql("""
SELECT risk_grade, COUNT(*) as total_funds
FROM fact_performance
GROUP BY risk_grade
ORDER BY total_funds DESC;
""", conn)

        risk_grade  total_funds
0         Moderate           16
1             High            8
2        Very High            6
3              Low            6
4  Moderately High            4

In [37]:
with open("queries.sql", "w") as f:
    f.write("""
-- 1. Top funds by AUM
SELECT scheme_name, aum_crore
FROM fact_performance
ORDER BY aum_crore DESC;

-- 2. SIP vs Lumpsum
SELECT transaction_type, COUNT(*), SUM(amount_inr)
FROM fact_transactions
GROUP BY transaction_type;

-- 3. State wise investment
SELECT state, SUM(amount_inr)
FROM fact_transactions
GROUP BY state
ORDER BY SUM(amount_inr) DESC;
""")

print("queries.sql created")

queries.sql created

In [38]:
with open("schema.sql", "w") as f:
    f.write("""
dim_fund(amfi_code PK)
fact_nav(amfi_code, date)
fact_transactions(...)
fact_performance(amfi_code,...)
""")

print("schema.sql created")

schema.sql created